on:
  push:

jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller -i meow.ico --onefile --version-file version.rc cobalt.py
      - run: ./dist/cobalt --github-actions 1 https://youtu.be/dQw4w9WgXcQ
      - uses: actions/upload-artifact@v4
        with:
          name: cobalt-${{ matrix.os }}
          path: dist/*
